routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::resource('todo-lists', 'TodoListsController');
Route::resource('todo-lists.todos', 'TodoController')->shallow();

Route::post('/todos/{todo}/done', 'TodoController@status')->name('status');
Route::post('/todos/{todo}/delay', 'TodoController@delay')->name('delay');

Route::resource('tags', 'TagController')->except('show');

Route::get('download', 'DownloadFileController')->name('download');

app/Models/Tag.php
<?php

namespace App\Models;

use App\Models\Todo;
use App\Scopes\SortAlphabeticallyScope;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = ['name'];

    public function todos()
    {
        return $this->belongsToMany(Todo::class)->withTimestamps();
    }

    public static function boot()
    {
        parent::boot();

        static::addGlobalScope(new SortAlphabeticallyScope);
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreTag;
use App\Models\Tag;

class TagController extends Controller
{
    public function index()
    {
       $tags = Tag::withCount('todos')->paginate(10);

        return view('tags.index', compact('tags'));
    }

    public function store(StoreTag $request)
    {
        $validatedData = $request->validated();

        $request->session()->flash('status', "Tag '$request->name' created");

        Tag::create($validatedData);

        return redirect()->back();
    }
}

resources/views/tags/buttons.blade.php
<div id="options" class="col-1 d-flex">
    <a href="" class="pr-2 btn">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16"><path fill-rule="evenodd" d="M1.679 7.932c.412-.621 1.242-1.75 2.366-2.717C5.175 4.242 6.527 3.5 8 3.5c1.473 0 2.824.742 3.955 1.715 1.124.967 1.954 2.096 2.366 2.717a.119.119 0 010 .136c-.412.621-1.242 1.75-2.366 2.717C10.825 11.758 9.473 12.5 8 12.5c-1.473 0-2.824-.742-3.955-1.715C2.92 9.818 2.09 8.69 1.679 8.068a.119.119 0 010-.136zM8 2c-1.981 0-3.67.992-4.933 2.078C1.797 5.169.88 6.423.43 7.1a1.619 1.619 0 000 1.798c.45.678 1.367 1.932 2.637 3.024C4.329 13.008 6.019 14 8 14c1.981 0 3.67-.992 4.933-2.078 1.27-1.091 2.187-2.345 2.637-3.023a1.619 1.619 0 000-1.798c-.45-.678-1.367-1.932-2.637-3.023C11.671 2.992 9.981 2 8 2zm0 8a2 2 0 100-4 2 2 0 000 4z"></path></svg>
    </a>

    <a href="" class="pr-2 btn">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16"><path fill-rule="evenodd" d="M11.013 1.427a1.75 1.75 0 012.474 0l1.086 1.086a1.75 1.75 0 010 2.474l-8.61 8.61c-.21.21-.47.364-.756.445l-3.251.93a.75.75 0 01-.927-.928l.929-3.25a1.75 1.75 0 01.445-.758l8.61-8.61zm1.414 1.06a.25.25 0 00-.354 0L10.811 3.75l1.439 1.44 1.263-1.263a.25.25 0 000-.354l-1.086-1.086zM11.189 6.25L9.75 4.81l-6.286 6.287a.25.25 0 00-.064.108l-.558 1.953 1.953-.558a.249.249 0 00.108-.064l6.286-6.286z"></path></svg>
    </a>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#exampleModalCenter">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16"><path fill-rule="evenodd" d="M6.5 1.75a.25.25 0 01.25-.25h2.5a.25.25 0 01.25.25V3h-3V1.75zm4.5 0V3h2.25a.75.75 0 010 1.5H2.75a.75.75 0 010-1.5H5V1.75C5 .784 5.784 0 6.75 0h2.5C10.216 0 11 .784 11 1.75zM4.496 6.675a.75.75 0 10-1.492.15l.66 6.6A1.75 1.75 0 005.405 15h5.19c.9 0 1.652-.681 1.741-1.576l.66-6.6a.75.75 0 00-1.492-.149l-.66 6.6a.25.25 0 01-.249.225h-5.19a.25.25 0 01-.249-.225l-.66-6.6z"></path></svg>
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Delete '{{ $tag->name }}'</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete '{{ $tag->name }}'?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary" onclick="document.getElementById('delete-form').submit();">Delete</button>
                </div>
            </div>
        </div>
    </div>


    <form id="delete-form" action="" method="POST">
        @csrf
        @method('DELETE')
    </form>
</div>

resources/views/tags/create.blade.php
<form id="createTagForm" action="{{ route('tags.store') }}" method="POST">
    @csrf
    <label for="name">Create new tag</label>
    <input type="text" name="name" class="form-control @error('name') is-invalid @enderror">
    @error('name')
        <div class="text-danger">{{ $message }}</div>
    @enderror
    <input type="submit" class="btn btn-info form-control mt-3" value="Create" form="createTagForm">
</form>

resources/views/tags/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-10">
                <h1>Tags</h1>
            </div>
            <div class="col-2">
                <a href="#" class="btn btn btn-primary">Create new tag</a>
            </div>
            <table class="table mt-3">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Used</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($tags as $tag)
                        <tr>
                            <td>{{ $tag->name }}</td>
                            <td data-toggle="tooltip" data-placement="right" title="@foreach($tag->todos as $todo) {{ '-'.$todo->title."\n" }} @endforeach">
                                {{ $tag->todos_count }}

                            </td>
                            <td class="float-right">
                                @include('tags.buttons')
                            </td>
                        </tr>
                    @empty
                        <p>No tags yet!</p>
                    @endforelse
                </tbody>
            </table>
            {{ $tags->links() }}
        </div>
    </div>

@endsection