routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::resource('todo-lists', 'TodoListsController');
Route::resource('todo-lists.todos', 'TodoController')->shallow();

Route::post('/todos/{todo}/done', 'TodoController@status')->name('status');
Route::post('/todos/{todo}/delay', 'TodoController@delay')->name('delay');

Route::resource('tags', 'TagController')->except('show');

Route::get('download', 'DownloadFileController')->name('download');

app/Models/TodoList.php
<?php

namespace App\Models;

use App\Models\User;
use App\Models\Todo;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class TodoList extends Model
{
    use softDeletes;

    protected $fillable = ['title', 'description'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function todos()
    {
        return $this->hasMany(Todo::class);
    }

    public function scopeSearch(Builder $query, String $search)
    {
        return $query->where(function($query) use ($search) {
            $query->where('title', 'like', '%' .$search. '%')
                ->orWhere('description', 'like', '%' .$search. '%');
        });
    }

    public function scopeMyLists(Builder $query)
    {
        return $query->where('user_id', auth()->user()->id);
    }

    protected static function boot()
    {
        parent::boot();

        static::deleting(function(TodoList $todoList) {
           $todoList->todos()->delete();
        });
    }
}

app/Http/Controllers/TodoListsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreTodoList;
use App\Models\TodoList;
use Illuminate\Http\Request;

class TodoListsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except('show');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->input('search') ?? '';

        $todoLists = TodoList::withCount(['todos', 'todos as todos_done_count' => function ($query) {
            $query->where('done', 1);
        }])->myLists()->search($search)->get();

        return view('todolists.index', compact('todoLists', 'search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('todolists.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTodoList $request)
    {
        $validatedData = $request->validated();

        $todoList = TodoList::make($validatedData);

        $todoList->user()->associate(auth()->user())->save();

//        TodoList::create(array_merge($validatedData, [
//            'user_id' => auth()->user()->id
//        ]));

        return redirect()->route('todo-lists.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(TodoList $todoList)
    {
        return redirect()->route('todo-lists.todos.index', $todoList);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(TodoList $todoList)
    {
        $this->authorize('todoList.update', $todoList);

        return view('todolists.edit', compact('todoList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreTodoList $request, TodoList $todoList)
    {
        $validatedData = $request->validated();

        $todoList->update($validatedData);

        return redirect()->route('todo-lists.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, TodoList $todoList)
    {
        $this->authorize('todoList.delete', $todoList);

        $todoList->delete($todoList);

        $request->session()->flash('status', 'Todo List deleted!');

        return redirect()->route('todo-lists.index');
    }
}

resources/views/todolists/_form.blade.php
@csrf
<div class="form-group">
    <label for="title">Title</label>
    <input type="text" name="title" class="form-control" id="title" placeholder="Title" value="{{ old('title') ?? $todoList->title ?? '' }}">
</div>
<div class="form-group">
    <label for="description">Description</label>
    <textarea name="description"
              id="description"
              rows="10"
              class="form-control"
              placeholder="Description">{{ old('description') ?? $todoList->description ?? '' }}
    </textarea>
</div>

resources/views/todolists/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h1>Create new Todo List</h1>
        </div>
        <form action="{{ route('todo-lists.store') }}" method="POST">
            @include('todolists._form')
            <input type="submit" value="Create" class="btn btn-primary">
        </form>
    </div>
@endsection

resources/views/todolists/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h1>Edit Todo List: {{$todoList->title}}</h1>
        </div>
        <form action="{{ route('todo-lists.update', [$todoList]) }}" method="POST">
            @method("PATCH")
            @include('todolists._form')
            <button type="submit" class="btn btn-primary">Edit</button>
        </form>
    </div>
@endsection

resources/views/todolists/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row d-flex justify-content-between mb-3">
            <h1>My todolists</h1>
            <a href="{{ route('todo-lists.create') }}" class="btn btn-primary h-50">Create new list</a>
        </div>
        <div class="row mb-3">
            <form action="{{ route('todo-lists.index') }}" method="GET" class="form-inline">
                <div class="form-group">
                    <input type="text" name="search" class="form-control" value="{{ isset($search) ? $search : '' }}">
                </div>
                <div class="form-group">
                    <input type="submit" value="search" class="btn btn-primary">
                </div>
            </form>
        </div>
        @forelse($todoLists as $todoList)
            @if($loop->first)
                <div class="row mb-3">
                    <div class="col-6">
                        <strong>Title</strong>
                    </div>
                    <div class="col-3">
                        <strong>Progress</strong>
                    </div>
                </div>
            @endif
            <div class="row">
                <div class="col-6">
                    <a href="{{ route('todo-lists.show', $todoList) }}">
                        {{ $todoList->title }}
                    </a>
                </div>
                <div class="col-3">
                    {{ $todoList->todos_done_count }}/{{ $todoList->todos_count }}
                </div>
                <div class="col-1 d-flex justify-content-between">
                    <a href="{{ route('todo-lists.show', [$todoList]) }}">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16"><path fill-rule="evenodd" d="M1.679 7.932c.412-.621 1.242-1.75 2.366-2.717C5.175 4.242 6.527 3.5 8 3.5c1.473 0 2.824.742 3.955 1.715 1.124.967 1.954 2.096 2.366 2.717a.119.119 0 010 .136c-.412.621-1.242 1.75-2.366 2.717C10.825 11.758 9.473 12.5 8 12.5c-1.473 0-2.824-.742-3.955-1.715C2.92 9.818 2.09 8.69 1.679 8.068a.119.119 0 010-.136zM8 2c-1.981 0-3.67.992-4.933 2.078C1.797 5.169.88 6.423.43 7.1a1.619 1.619 0 000 1.798c.45.678 1.367 1.932 2.637 3.024C4.329 13.008 6.019 14 8 14c1.981 0 3.67-.992 4.933-2.078 1.27-1.091 2.187-2.345 2.637-3.023a1.619 1.619 0 000-1.798c-.45-.678-1.367-1.932-2.637-3.023C11.671 2.992 9.981 2 8 2zm0 8a2 2 0 100-4 2 2 0 000 4z"></path></svg>
                    </a>
                    <a href="{{ route('todo-lists.edit', [$todoList]) }}">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16"><path fill-rule="evenodd" d="M11.013 1.427a1.75 1.75 0 012.474 0l1.086 1.086a1.75 1.75 0 010 2.474l-8.61 8.61c-.21.21-.47.364-.756.445l-3.251.93a.75.75 0 01-.927-.928l.929-3.25a1.75 1.75 0 01.445-.758l8.61-8.61zm1.414 1.06a.25.25 0 00-.354 0L10.811 3.75l1.439 1.44 1.263-1.263a.25.25 0 000-.354l-1.086-1.086zM11.189 6.25L9.75 4.81l-6.286 6.287a.25.25 0 00-.064.108l-.558 1.953 1.953-.558a.249.249 0 00.108-.064l6.286-6.286z"></path></svg>
                    </a>
                    <form action="{{ route('todo-lists.destroy', [$todoList]) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <label>
                        <input type="submit" style="display: none;">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16"><path fill-rule="evenodd" d="M6.5 1.75a.25.25 0 01.25-.25h2.5a.25.25 0 01.25.25V3h-3V1.75zm4.5 0V3h2.25a.75.75 0 010 1.5H2.75a.75.75 0 010-1.5H5V1.75C5 .784 5.784 0 6.75 0h2.5C10.216 0 11 .784 11 1.75zM4.496 6.675a.75.75 0 10-1.492.15l.66 6.6A1.75 1.75 0 005.405 15h5.19c.9 0 1.652-.681 1.741-1.576l.66-6.6a.75.75 0 00-1.492-.149l-.66 6.6a.25.25 0 01-.249.225h-5.19a.25.25 0 01-.249-.225l-.66-6.6z"></path></svg>
                        </label>
                    </form>
                </div>
            </div>
        @empty
            <p>No todo lists found!</p>
        @endforelse
    </div>
@endsection

resources/views/todolists/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
       <h1>{{ $todoList->title  }}</h1>
        <p>{{ $todoList->description }}</p>
        <hr>
        <p class="text-muted">{{ $todoList->created_at->diffForHumans() }}</p>
    </div>
@endsection