routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::resource('todo-lists', 'TodoListsController');
Route::resource('todo-lists.todos', 'TodoController')->shallow();

Route::post('/todos/{todo}/done', 'TodoController@status')->name('status');
Route::post('/todos/{todo}/delay', 'TodoController@delay')->name('delay');

Route::resource('tags', 'TagController')->except('show');

Route::get('download', 'DownloadFileController')->name('download');

app/Models/Todo.php
<?php

namespace App\Models;

use App\Models\Tag;
use App\Models\TodoList;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Todo extends Model
{
    use softDeletes;

    protected $fillable = ['title', 'description', 'done', 'file', 'deadline', 'url'];

    public function todoList()
    {
        return $this->belongsTo(TodoList::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class)->withTimestamps();
    }

    public function toggleStatus()
    {
        $this->done = !$this->done;

        return $this;
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreTag;
use App\Models\Tag;

class TagController extends Controller
{
    public function index()
    {
       $tags = Tag::withCount('todos')->paginate(10);

        return view('tags.index', compact('tags'));
    }

    public function store(StoreTag $request)
    {
        $validatedData = $request->validated();

        $request->session()->flash('status', "Tag '$request->name' created");

        Tag::create($validatedData);

        return redirect()->back();
    }
}

app/Http/Controllers/TodoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreTodo;
use App\Models\Tag;
use App\Models\Todo;
use App\Models\TodoList;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class TodoController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except('index');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(TodoList $todoList, Request $request)
    {
        $todoList = TodoList::withCount(['todos', 'todos as todos_done_count' => function ($query) {
            $query->where('done', 1);
        }])->where('id', $todoList->id)->first();

        $todos = Todo::where('todo_list_id', $todoList->id);

        if(isset($request->tagFilter)) {
            $todos = $todos->whereHas('tags', function (Builder $q) use ($request) {
                $q->where('tags.id', $request->tagFilter);
            });
        }

        $todos = $todos->orderBy('done')->orderBy('deadline')->get();

        $tags = Tag::whereHas('todos', function($query) use ($todoList) {
            $query->where('todo_list_id', $todoList->id);
        })->distinct()->get();

        // status progress bar
        $status = $todoList->todos_count != 0 ? intval($todoList->todos_done_count/$todoList->todos_count*100) : null;

        return view('todos.index', compact('todoList', 'status', 'todos', 'tags'))->with('tagFilter', $request->tagFilter);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(TodoList $todoList)
    {
        $this->authorize('todo.create', $todoList);

        $tags = Tag::all();

        return view('todos.create', compact('todoList', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreTodo $request, TodoList $todoList)
    {
        $request->validated();

        // store file
        if($request->hasFile('file')){
            $file = $request->file('file');
            $path = $file->store('files','public');
        }

        $todo = Todo::make(array_merge($request->validated(), [
            'file' => $path ?? null
        ]));

        $todo->todoList()->associate($todoList)->save();

        // attach tags
        $tags = $request->input('tags');
        $todo->tags()->attach($tags);

        $request->session()->flash('status', 'Todo created');

        return redirect()->route('todo-lists.todos.index', $todoList);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Todo $todo)
    {
        return view('todos.show', compact('todo'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Todo $todo)
    {
        $this->authorize('todo.update', $todo);

        $tags = Tag::all();

        return view('todos.edit', compact('todo', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StoreTodo $request, Todo $todo)
    {
        $validatedData = $request->validated();

        if($request->hasFile('file')){
            $file = $request->file('file');
            $path = $file->store('files','public');
        }

        // attach tags
        $tags = $request->input('tags');
        $todo->tags()->sync($tags);

        $todo->update(array_merge($validatedData, [
            'file' => $path ?? null
        ]));

        $request->session()->flash('status', 'Todo updated');

        return redirect()->route('todo-lists.show', [$todo->todoList]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Request $request
     * @param Todo $todo
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Request $request, Todo $todo)
    {
        $this->authorize('todo.delete', $todo);

        Storage::delete($todo->file);

        $todo->delete();

        $request->session()->flash('status', 'Todo deleted');

        return redirect()->back();
    }

    public function status(Request $request, Todo $todo)
    {
        $this->authorize('todo.update', $todo);

        $todo->toggleStatus()->save();

        $message = "Status '$todo->title' changed to: ".($todo->done ? 'Done' : "Todo");

        $request->session()->flash('status', $message);

        return redirect()->back();
    }

    public function delay(Request $request, Todo $todo)
    {
        $this->authorize('todo.update', $todo);

        $deadline = new Carbon($todo->deadline);

        $todo->deadline = $deadline->addDays((int)$request->delay);
        $todo->save();

        $request->session()->flash('status', "$request->delay days added to '$todo->title'");

        return redirect()->route('todo-lists.todos.index', $todo->todoList);
    }
}

resources/views/todos/_delay.blade.php
@can('todo.update', $todo)
    @if(!$todo->done && $todo->deadline)
        <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#model{{ $todo->id }}">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path d="M12.5 7.25a.75.75 0 00-1.5 0v5.5c0 .27.144.518.378.651l3.5 2a.75.75 0 00.744-1.302L12.5 12.315V7.25z"></path><path fill-rule="evenodd" d="M12 1C5.925 1 1 5.925 1 12s4.925 11 11 11 11-4.925 11-11S18.075 1 12 1zM2.5 12a9.5 9.5 0 1119 0 9.5 9.5 0 01-19 0z"></path></svg>
        </button>

        <div class="modal fade" id="model{{ $todo->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Delay '{{ $todo->title }}'</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form action="{{ route('delay', $todo) }}" method="POST" id="delay-form">
                            @csrf
                            <div class="form-group">
                                <label for="recipient-name" class="col-form-label"></label>
                                Delay the todo with
                                <select name="delay">
                                    @foreach(range(1,14) as $day)
                                        <option value="{{ $day }}">{{ $day }}</option>
                                    @endforeach
                                </select>
                                days
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                                <button type="submit" class="btn btn-primary">Oke</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    @endif
@endcan

resources/views/todos/_form.blade.php
@csrf

<div class="form-group">
    <label for="title">Title</label>
    <input type="text"
           name="title"
           class="form-control @error('title') is-invalid @enderror"
           id="title"
           placeholder="Title"
            value="{{ old('title') ?? $todo->title ?? '' }}">
    @error('title')
        <div class="text-danger">{{ $message }}</div>
    @enderror
</div>

<div class="form-group">
    <label for="description">Description</label>
    <textarea name="description"
              id="description"
              rows="10"
              class="form-control @error('description') is-invalid @enderror"
              placeholder="Description"
    >{{ old('description') ?? $todo->description ?? '' }}</textarea>
    @error('description')
        <div class="text-danger">{{ $message }}</div>
    @enderror
</div>


<div class="form-group">
    <label class="mdb-main-label d-flex" for="tags">Tags (max 3)</label>
    <select name="tags[]" class="form-control md-form selectpicker @error('tags') is-invalid @enderror" multiple>
        @foreach($tags as $tag)
            <option value="{{ $tag->id }}" @if(isset($todo)){{ $todo->tags()->find($tag->id) ? 'selected' : '' }} @endif>{{ $tag->name }}</option>
        @endforeach
    </select>
    @error('tags')
        <div class="text-danger">{{ $message }}</div>
    @enderror
</div>

<div class="form-group">
    <label for="url">Url</label>
    <input type="text"
           name="url"
           id="url"
           class="form-control @error('url') is-invalid @enderror"
           value="{{ old('url') ?? $todo->url ?? '' }}">
    @error('url')
    <div class="text-danger">{{ $message }}</div>
    @enderror
</div>

<div class="form-group">
    <label for="file">File</label>
    <input type="file"
           name="file"
           id="file"
           class="form-control-file @error('file') is-invalid @enderror">
    @error('file')
        <div class="text-danger">{{ $message }}</div>
    @enderror
</div>

<div class="form-group">
    <label for="deadline">Deadline</label>
    <input type="datetime-local"
           id="deadline"
           name="deadline"
           value="{{ old('deadline') ?? (isset($todo) ? Carbon\Carbon::parse($todo->deadline)->toDateTimeLocalString() : '') }}"
           class="d-block form-control @error('deadline') is-invalid @enderror">
    @error('deadline')
        <div class="text-danger">{{ $message }}</div>
    @enderror
</div>

resources/views/todos/buttons.blade.php
<div id="options" class="col-1 d-flex">
    <a href="{{ route('todos.show', $todo) }}" class="pr-2 btn">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16"><path fill-rule="evenodd" d="M1.679 7.932c.412-.621 1.242-1.75 2.366-2.717C5.175 4.242 6.527 3.5 8 3.5c1.473 0 2.824.742 3.955 1.715 1.124.967 1.954 2.096 2.366 2.717a.119.119 0 010 .136c-.412.621-1.242 1.75-2.366 2.717C10.825 11.758 9.473 12.5 8 12.5c-1.473 0-2.824-.742-3.955-1.715C2.92 9.818 2.09 8.69 1.679 8.068a.119.119 0 010-.136zM8 2c-1.981 0-3.67.992-4.933 2.078C1.797 5.169.88 6.423.43 7.1a1.619 1.619 0 000 1.798c.45.678 1.367 1.932 2.637 3.024C4.329 13.008 6.019 14 8 14c1.981 0 3.67-.992 4.933-2.078 1.27-1.091 2.187-2.345 2.637-3.023a1.619 1.619 0 000-1.798c-.45-.678-1.367-1.932-2.637-3.023C11.671 2.992 9.981 2 8 2zm0 8a2 2 0 100-4 2 2 0 000 4z"></path></svg>
    </a>

    @can('todo.update', $todo)
        @if(!$todo->done)
            <a href="{{ route('todos.edit', $todo) }}" class="pr-2 btn">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16"><path fill-rule="evenodd" d="M11.013 1.427a1.75 1.75 0 012.474 0l1.086 1.086a1.75 1.75 0 010 2.474l-8.61 8.61c-.21.21-.47.364-.756.445l-3.251.93a.75.75 0 01-.927-.928l.929-3.25a1.75 1.75 0 01.445-.758l8.61-8.61zm1.414 1.06a.25.25 0 00-.354 0L10.811 3.75l1.439 1.44 1.263-1.263a.25.25 0 000-.354l-1.086-1.086zM11.189 6.25L9.75 4.81l-6.286 6.287a.25.25 0 00-.064.108l-.558 1.953 1.953-.558a.249.249 0 00.108-.064l6.286-6.286z"></path></svg>
            </a>
        @endif
    @endcan

    @can('todo.delete', $todo)
    <!-- Button trigger modal -->
        <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#exampleModalCenter">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16"><path fill-rule="evenodd" d="M6.5 1.75a.25.25 0 01.25-.25h2.5a.25.25 0 01.25.25V3h-3V1.75zm4.5 0V3h2.25a.75.75 0 010 1.5H2.75a.75.75 0 010-1.5H5V1.75C5 .784 5.784 0 6.75 0h2.5C10.216 0 11 .784 11 1.75zM4.496 6.675a.75.75 0 10-1.492.15l.66 6.6A1.75 1.75 0 005.405 15h5.19c.9 0 1.652-.681 1.741-1.576l.66-6.6a.75.75 0 00-1.492-.149l-.66 6.6a.25.25 0 01-.249.225h-5.19a.25.25 0 01-.249-.225l-.66-6.6z"></path></svg>
        </button>

        <!-- Modal -->
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLongTitle">Delete '{{ $todo->title }}'</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Are you sure you want to delete '{{ $todo->title }}'?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <button type="button" class="btn btn-danger" onclick="document.getElementById('delete-form').submit();">Delete</button>
                    </div>
                </div>
            </div>
        </div>


        <form id="delete-form" action="{{ route('todos.destroy', [$todo]) }}" method="POST">
            @csrf
            @method('DELETE')
        </form>
    @endcan
</div>

resources/views/todos/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h1>Create new todo</h1>
        </div>
        <div class="row">
            <div class="col-9">
                <form method="POST" action="{{ route('todo-lists.todos.store', $todoList) }}" enctype="multipart/form-data">

                   @include('todos._form')

                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary">
                        <a href="{{ url()->previous() }}" class="btn-link ml-2">Back</a>
                    </div>
                </form>
            </div>

            {{-- create new Tag--}}
            <div class="col-3">
                <div class="form-group border-left pl-2">
                    @include('tags.create')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/todos/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h1>Edit todo '{{ $todo->title }}'</h1>
        </div>
        <div class="row">
            <div class="col-9">
                <form method="POST" action="{{ route('todos.update', $todo) }}" enctype="multipart/form-data">
                    @method('PATCH')
                    @include('todos._form')

                    <div class="form-group">
                        <input type="submit" value="Edit" class="btn btn-primary">
                    </div>
                </form>
            </div>

            {{-- create new Tag--}}
            <div class="col-3">
                <div class="form-group border-left pl-2">
                    @include('tags.create')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/todos/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row d-flex justify-content-between mb-3">
            <h1>
                {{ $todoList->title }}
                @if($todoList->todos_count === $todoList->todos_done_count)
                    (Completed)
                @endif
            </h1>

            <form action="{{ route('todo-lists.todos.index', $todoList) }}" class="form-inline">
                <select class="form-control" name="tagFilter">
                    <option disabled selected>Select Tag</option>
                    <option value="">All</option>
                    @foreach($tags as $tag)
                        <option value="{{ $tag->id }}" {{ $tagFilter == $tag->id ? 'selected' : ''}}>{{ $tag->name }}</option>
                    @endforeach
                </select>
                <input type="submit" value="Filter" class="btn btn-outline-primary ml-2">
            </form>

            @can('todo.create', $todoList)
                <a href="{{ route('todo-lists.todos.create', $todoList) }}" class="btn btn-primary h-50">{{ __('Create Todo') }}</a>
            @endcan
        </div>
        <div class="row mb-4">
            <p class="text-black-50">{{ $todoList->description }}</p>
        </div>

        @if($status)
            <div class="progress mb-4">
                <div class="progress-bar"
                     role="progressbar"
                     style="width: {{ $status }}%"
                     aria-valuenow="{{ $status }}"
                     aria-valuemin="{{ $status }}"
                     aria-valuemax="100">
                    <span>{{ $status }}%</span>
                </div>

            </div>
        @endif

        <div class="table-responsive">
             @forelse($todos as $todo)
                 @if($loop->first)
                    <table class="table">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Title</th>
                                <th></th>
                                <th>Tags</th>
                                <th>Deadline</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                    @endif
                     <tr style="@if($todo->done) background-color: #e3f2fd; @endif
                                @if(!$todo->done && $todo->deadline && $todo->deadline <= now()) background-color: #ff6900 @endif">
                        <td>
                            @include('todos._delay')
                        </td>
                        <td>
                            {{ $todo->title }}
                        </td>
                        <td>
                            @if($todo->file)
                                <a href="{{ route('download', ['file' => $todo->file]) }}">file</a>
                            @endif
                        </td>
                         <td>
                             <h5>
                                @foreach($todo->tags as $tag)
                                    <span class="badge badge-info ">
                                        <a class="text-light"
                                           href="{{ route('todo-lists.todos.index', ['todo_list' => $todoList, 'tagFilter' => $tag]) }}">
                                            {{ $tag->name }}
                                        </a>
                                    </span>
                                 @endforeach
                             </h5>
                         </td>
                        <td>
                            <p data-toggle="{{ $todo->deadline <= now()->addDays(7) }}" data-placement="bottom" title="{{ Carbon\Carbon::parse($todo->deadline)->format('d-m-Y (h:m)') }}">
                                {{ $todo->deadline ? Carbon\Carbon::parse($todo->deadline)->diffForHumans() : "-" }}

                                @if($todo->deadline <= now()->addDays(2) &&  $todo->deadline && !$todo->done)
                                        <svg style="fill:red;" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16"><path fill-rule="evenodd" d="M8.22 1.754a.25.25 0 00-.44 0L1.698 13.132a.25.25 0 00.22.368h12.164a.25.25 0 00.22-.368L8.22 1.754zm-1.763-.707c.659-1.234 2.427-1.234 3.086 0l6.082 11.378A1.75 1.75 0 0114.082 15H1.918a1.75 1.75 0 01-1.543-2.575L6.457 1.047zM9 11a1 1 0 11-2 0 1 1 0 012 0zm-.25-5.25a.75.75 0 00-1.5 0v2.5a.75.75 0 001.5 0v-2.5z"></path></svg>
                                @endif
                            </p>
                        </td>
                         <td>
                             <form id="status-form" action="{{ route('status', [$todo]) }}" method="POST">
                                 @csrf
                                 <input type="checkbox" @cannot('todo.update', $todo)disabled="disabled" @endcannot
                                        @if($todo->done) checked @endif onchange="this.form.submit()">
                             </form>
                         </td>

                         <td class="float-right">
                             @include('todos.buttons')
                         </td>
                     </tr>
                 @empty
                    <p>No todos yet! Click <a href="{{ route('todo-lists.todos.create', $todoList) }}">HERE</a> to create one!</p>
                 @endforelse
                </tbody>
            </table>
        </div>
    </div>
@endsection

resources/views/todos/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <h1>
                <span class="mr-3">
                    {{ $todo->title }}
                </span>
                @foreach($todo->tags as $tag)
                    <span class="badge badge-info">
                       {{ $tag->name }}
                    </span>
                @endforeach
            </h1>
        </div>

        <div class="row">
            <p class="text-muted">
                {{ $todo->description }}
            </p>
        </div>
        <hr>
        <div class="row">
            @if($todo->deadline)
                <p>Deadline: {{ $todo->deadline }}  ({{ Carbon\Carbon::parse($todo->deadline)->diffForHumans() }})</p>
            @endif
        </div>

        <div class="row">
            @if($todo->url)
                <p>
                    Url: <a href="{{ $todo->url }}" target="_blank">{{ $todo->url }}</a>
                </p>
            @endif
        </div>

        <div class="row">
            @if($todo->file)
                <p>
                    File: <a href="{{ route('download', ['file' => $todo->file]) }}"> Download</a>
                </p>
            @endif
        </div>

        <div class="row">
            <a href="{{ url()->previous() }}" class="btn btn-primary">Go Back</a>
        </div>
    </div>
@endsection